added user auth
with0p/gophermart pull request #1
Opened 2024-09-08 13:38 UTC by with0p

2024-09-19 21:39 UTC, tmvrus requested changes
- fmt.Println не предназначен для логирования, это материал второго спринта. если лень тащить в проект новую библиотеку, то можно взять slog
- не стоит игнорировать ошибки, их следует хотя бы логировать

2024-09-19 21:39 UTC, tmvrus commented on cmd/gophermart/main.go
> +	}
тут работа продолжится если будет ошибка, и случится паника

2024-09-19 21:39 UTC, tmvrus commented on cmd/gophermart/main.go
> +	}
а вот это зачем?

2024-09-19 21:39 UTC, tmvrus commented on cmd/gophermart/main.go
> +	// //run periodic queue feed to process unfinished orders
выглядит как лишние // в комментах

2024-09-19 21:39 UTC, tmvrus commented on internal/service/service-gophermart.go
> +func worker(jobs <-chan models.OrderID, wg *sync.WaitGroup, s *ServiceGophermart, ctx context.Context, accrualAddr string) {
контекст обычно передают первым аргументом, советую придерживаться этого правила

2024-09-19 21:39 UTC, tmvrus commented on internal/service/service-gophermart.go
> +			continue
ошибку надо хотя бы логировать

2024-09-19 21:39 UTC, tmvrus commented on internal/service/service-gophermart.go
> +func getOrderDataFromAccrual(orderID models.OrderID, accrualAddr string) (*models.OrderExternalData, error) {
неплохо бы и сюда контекст передавать, раз уж он есть у вызывающей ф-и, и создавать запрос с ним: `http.NewRequestWithContext`

2024-09-19 21:39 UTC, tmvrus commented on internal/service/service-gophermart.go
> +	}
а где обрабатывается [429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) (Too Many Requests)

2024-09-19 21:39 UTC, tmvrus commented on internal/service/service-gophermart.go
> +	defer cancel()
а зачем создавать отменяемый контекст если он отменяется только в defer?

2024-09-19 21:39 UTC, tmvrus commented on internal/service/service-gophermart.go
> +	defer resp.Body.Close()
если сервис вернет например 500 и какой-то body то этот код никогда не выполнится

2024-09-19 21:39 UTC, tmvrus commented on internal/storage/storage-db.go
> +	}
в этом коде нет никакого смысла, драйвер сам отменит запрос если контекст будет отменен, это касается всех методов в storage

2024-09-19 21:39 UTC, tmvrus commented on internal/service/service-gophermart.go
> +	return s.storage.AddWithdrawal(ctx, userID, orderID, amount)
представь ситуацию:
- приходит 3 запроса на списание 100 баллов 
- все 3 вычитывает баланс, доступно 100 баллов для списания
- все 3 производят списание

что будет с балансом?

2024-09-19 21:39 UTC, tmvrus commented on internal/service/service-gophermart.go
> +		}
не стоит игнорировать ошибки

2024-09-19 21:39 UTC, tmvrus commented on internal/storage/storage-db.go
> +		if err == sql.ErrNoRows {
использовать прямое сравнение ошибок ненадежный способ, следует использовать errors.Is это материал 3го спринта

2024-09-19 21:39 UTC, tmvrus commented on internal/storage/storage-db.go
> +			errInsert = customerror.ErrUniqueKeyConstrantViolation
а можно просто `return customerror.ErrUniqueKeyConstrantViolation`

2024-09-19 21:39 UTC, tmvrus commented on internal/storage/storage-db.go
> +func (s *StorageDB) ValidateUser(ctx context.Context, login string, password string) error {
когда тип аргументов, идущих подряд, совпадает, можно переписать вот так:
`login string, password string` -> `login, password string`

2024-09-20 07:14 UTC, with0p commented on internal/service/service-gophermart.go
> +	return s.storage.AddWithdrawal(ctx, userID, orderID, amount)
три заказа от одного пользователя одновременно? смотрю постановку, не вполне понимаю, как получить описанную выше ситуацию
```
#### **Запрос на списание средств**

Хендлер: `POST /api/user/balance/withdraw`

Хендлер доступен только авторизованному пользователю. Номер заказа представляет собой гипотетический номер нового заказа пользователя в счет оплаты которого списываются баллы.

Примечание: для успешного списания достаточно успешной регистрации запроса, никаких внешних систем начисления не предусмотрено и не требуется реализовывать.

Формат запроса:

```
POST /api/user/balance/withdraw HTTP/1.1
Content-Type: application/json

{
	"order": "2377225624",
    "sum": 751
}
```

Здесь `order` — номер заказа, а `sum` — сумма баллов к списанию в счёт оплаты.

Возможные коды ответа:

- `200` — успешная обработка запроса;
- `401` — пользователь не авторизован;
- `402` — на счету недостаточно средств;
- `422` — неверный номер заказа;
- `500` — внутренняя ошибка сервера.
```

2024-09-20 07:16 UTC, with0p commented on internal/service/service-gophermart.go
> +	return s.storage.AddWithdrawal(ctx, userID, orderID, amount)
насколько я понимаю, метод списания у нас синхронный, то есть все три запроса не смогут получить одинаковый баланс, равный первому

2024-09-20 09:00 UTC, tmvrus commented on internal/service/service-gophermart.go
> +	return s.storage.AddWithdrawal(ctx, userID, orderID, amount)
это явно прописано в ТЗ?

2024-09-20 09:01 UTC, tmvrus commented on internal/service/service-gophermart.go
> +	return s.storage.AddWithdrawal(ctx, userID, orderID, amount)
Хотя если и было бы прописано, кто гарантирует что коллеги будут соблюдать контракт и ничего не сломают?

2024-09-20 09:37 UTC, with0p commented on internal/service/service-gophermart.go
> +	return s.storage.AddWithdrawal(ctx, userID, orderID, amount)
если у нас только один поток работает, я не панимаю, как мы одновременно запросим три раза по одному и тому же пользователю баланс. или тут тоже надо многопоточность прикручивать с очередями и этим всем? это задача со звездочкой? :)

2024-09-20 09:59 UTC, with0p commented on internal/service/service-gophermart.go
> +	return s.storage.AddWithdrawal(ctx, userID, orderID, amount)
в задании явно не прописано ни о каком методе, синхронный он или нет. асинхронность при получении баллов понятна, потому что там мы общаемся с третьим сервисом, у которого процесс обработки идет по шагам. а здесь ничего подобного нет - поэтому решение вот такое.
может быть, здесь нужны мьютексы?

2024-09-20 10:00 UTC, with0p commented on internal/service/service-gophermart.go
> +	return s.storage.AddWithdrawal(ctx, userID, orderID, amount)
но они не имеют смысла, если поток один. запуталась, в общем

2024-09-20 14:15 UTC, with0p commented on cmd/gophermart/main.go
> +	}
поправила, спасибо

2024-09-20 14:16 UTC, with0p commented on cmd/gophermart/main.go
> +	}
убрала, осталось от попыток починить тесты

2024-09-20 14:16 UTC, with0p commented on cmd/gophermart/main.go
> +	// //run periodic queue feed to process unfinished orders
убрала, спасибо

2024-09-20 14:16 UTC, with0p commented on internal/service/service-gophermart.go
> +func worker(jobs <-chan models.OrderID, wg *sync.WaitGroup, s *ServiceGophermart, ctx context.Context, accrualAddr string) {
поправила, спасибо

2024-09-20 14:16 UTC, with0p commented on internal/service/service-gophermart.go
> +			continue
добавила лог

2024-09-20 14:17 UTC, with0p commented on internal/service/service-gophermart.go
> +func getOrderDataFromAccrual(orderID models.OrderID, accrualAddr string) (*models.OrderExternalData, error) {
добавила и поменяла логику выполнения гет-запроса

2024-09-20 14:18 UTC, with0p commented on internal/service/service-gophermart.go
> +	}
добавила обработку, но не вполне уверена, что мой способ хороший. выбрала его, потому что показалось удобным так останавливать все горутины и затем беспроблемно возобновлять их работу

2024-09-20 14:18 UTC, with0p commented on internal/service/service-gophermart.go
> +	defer cancel()
да, поправила, спасибо

2024-09-20 14:18 UTC, with0p commented on internal/service/service-gophermart.go
> +	defer resp.Body.Close()
изменила порядок обработки запроса

2024-09-20 14:24 UTC, with0p commented on internal/storage/storage-db.go
> +		if err == sql.ErrNoRows {
да, спасибо, забыла поправить

2024-09-20 14:24 UTC, with0p commented on internal/storage/storage-db.go
> +	}
почистила методы

2024-09-20 14:28 UTC, with0p commented on internal/service/service-gophermart.go
> +		}
добавила логирование

2024-09-20 14:29 UTC, with0p commented
> * fmt.Println не предназначен для логирования, это материал второго спринта. если лень тащить в проект новую библиотеку, то можно взять slog
> * не стоит игнорировать ошибки, их следует хотя бы логировать

спасибо, поправила по комментариям, остается только вопрос со списанием

2024-09-20 15:23 UTC, with0p commented on internal/service/service-gophermart.go
> +	return s.storage.AddWithdrawal(ctx, userID, orderID, amount)
добавила лок записей в бд на время транзакции получения баланса и добавления списания, мб речь была об этом

2024-09-24 11:18 UTC, tmvrus approved these changes
Все верно, зачастую лок это самый быстрый и простой способ добиться консистентности.

2024-09-24 11:27 UTC, merged